name: Spring Boot CI/CD with MySQL and Redis

on:
  push:
    branches:
      - master  # Change to 'master'
  pull_request:
    branches:
      - master  # Change to 'master'
  workflow_dispatch:  # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DockerDemo

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'


          
      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      # Start MySQL, Redis, and Spring Boot application with Docker Compose
      - name: Start Docker Compose
        run: |
          docker-compose up -d

      # Wait for MySQL and Redis to be ready
      - name: Wait for services to be ready
        run: sleep 30


      # List all Docker containers
      - name: List Docker containers
        run: |
                 docker ps -a

      # Check if the server is running and responding
      - name: Check server health
        run: |
          curl -f http://localhost:8080/hello?myName=bhavna || exit 1

      # Shut down Docker Compose services
      - name: Shut down services
        run: docker-compose down
