name: Spring Boot CI/CD with MySQL and Redis

on:
  push:
    branches:
      - master  # Change to 'master'
  pull_request:
    branches:
      - master  # Change to 'master'
  workflow_dispatch:  # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DockerDemo

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      # Start MySQL, Redis, and Spring Boot application with Docker Compose
      - name: Start Docker Compose
        run: |
          docker compose up -d

      # List all Docker containers
      - name: List Docker containers
        run: |
          docker ps -a

      - name: Check logs
        run: |
          docker logs spring-boot-app-container 


      # List all Docker containers
      - name: List Docker containers
        run: |
                 docker ps -a

      - name: Check Spring Boot logs
        run: docker-compose -f DockerDemo/docker-compose.yml logs app

      # Check if the server is running and responding
      - name: Check server health
        run: |
          curl -f http://localhost:8082/hello?myName=bhavna || exit 1

      # Shut down Docker Compose services
      - name: Shut down services
        run: docker-compose down
